keyword_depluralizer <- function(keywords) {
  library(tidyverse)
  library(stringr)
  
  keywords<- keywords %>% mutate(singular=edited)  

  keywords$singular<-str_replace(keywords$singular, "acorns","acorn")
  keywords$singular<-str_replace(keywords$singular, "acoustics","acoustic")
  keywords$singular<-str_replace(keywords$singular, "adults","adult")
  keywords$singular<-str_replace(keywords$singular, "adaptations","adaptation")
  keywords$singular<-str_replace(keywords$singular, "aflps", "aflp")
  keywords$singular<-str_replace(keywords$singular, "aggregates","aggregate")
  keywords$singular<-str_replace(keywords$singular, "aggregations","aggregation")
  keywords$singular<-str_replace(keywords$singular, "alkaloids","alkaloid")
  keywords$singular<-str_replace(keywords$singular, "alleles","allele")
  keywords$singular<-str_replace(keywords$singular, "allelochemicals","allelochemical")
  keywords$singular<-str_replace(keywords$singular, "allozymes","allozyme")
  keywords$singular<-str_replace(keywords$singular, "alozymes","allozyme")
  keywords$singular<-str_replace(keywords$singular, "alozyme", "allozyme")
  keywords$singular<-str_replace(keywords$singular, "amphibians", "amphibian")
  keywords$singular<-str_replace(keywords$singular, "amphipods","amphipod")
  keywords$singular<-str_replace(keywords$singular, "analyses", "analysis")
  keywords$singular<-str_replace(keywords$singular, "angiosperms","angiosperm")
  keywords$singular<-str_replace(keywords$singular, "animals","animal")
  keywords$singular<-str_replace(keywords$singular, "annuals","annual")
  keywords$singular<-str_replace(keywords$singular, "anthocyanins","anthocyanin")
  keywords$singular<-str_replace(keywords$singular, "antibiotics","antibiotic")
  keywords$singular<-str_replace(keywords$singular, "ants", "ant")
  keywords$singular<-str_replace(keywords$singular, "anurans","anuran")
  keywords$singular<-str_replace(keywords$singular, "aphids","aphid")
  keywords$singular<-str_replace(keywords$singular, "approaches","approach")
  keywords$singular<-str_replace(keywords$singular, "approximations", "approximation")
  keywords$singular<-str_replace(keywords$singular, "archipelagoes","archipelago")
  keywords$singular<-str_replace(keywords$singular, "areas", "area")
  keywords$singular<-str_replace(keywords$singular, "aridlands","aridland")
  keywords$singular<-str_replace(keywords$singular, "arthropods","arthropod")
  keywords$singular<-str_replace(keywords$singular, "assemblages","assemblage")
  keywords$singular<-str_replace(keywords$singular, "associations", "association")
  keywords$singular<-str_replace(keywords$singular, "attitudes","attitude")
  keywords$singular<-str_replace(keywords$singular, "attractors","attractor")
  keywords$singular<-str_replace(keywords$singular, "autosomes","autosome")
  keywords$singular<-str_replace(keywords$singular, "baboons","baboon")
  keywords$singular<-str_replace(keywords$singular, "barnacles","barnacle")
  keywords$singular<-str_replace(keywords$singular, "barriers","barrier")
  keywords$singular<-str_replace(keywords$singular, "beaches","beach")
  keywords$singular<-str_replace(keywords$singular, "beetles","beetle")
  keywords$singular<-str_replace(keywords$singular, "benefits", "benefit")
  keywords$singular<-str_replace(keywords$singular, "bibliometrics","bibliometric")
  keywords$singular<-str_replace(keywords$singular, "bioacoustics","bioacoustic")
  keywords$singular<-str_replace(keywords$singular, "bioenergetics","bioenergetic")
  keywords$singular<-str_replace(keywords$singular, "biofilms","biofilm")
  keywords$singular<-str_replace(keywords$singular, "bioindicators","bioindicator")
  keywords$singular<-str_replace(keywords$singular, "biomarkers","biomarker")
  keywords$singular<-str_replace(keywords$singular, "biomechanics","biomechanic")
  keywords$singular<-str_replace(keywords$singular, "biomes","biome")
  keywords$singular<-str_replace(keywords$singular, "birds", "bird")
  keywords$singular<-str_replace(keywords$singular, "bivalves","bivalve")
  keywords$singular<-str_replace(keywords$singular, "blooms","bloom")
  keywords$singular<-str_replace(keywords$singular, "borders","border")
  keywords$singular<-str_replace(keywords$singular, "bottlenecks","bottleneck")
  keywords$singular<-str_replace(keywords$singular, "breeders", "breeder")
  keywords$singular<-str_replace(keywords$singular, "bristles","bristle")
  keywords$singular<-str_replace(keywords$singular, "bromeliads","bromeliad")
  keywords$singular<-str_replace(keywords$singular, "browsers","browser")
  keywords$singular<-str_replace(keywords$singular, "bryophytes","bryophyte")
  keywords$singular<-str_replace(keywords$singular, "bryozoans","bryozoan")
  keywords$singular<-str_replace(keywords$singular, "budgets","budget")
  keywords$singular<-str_replace(keywords$singular, "bulbuls","bulbul")
  keywords$singular<-str_replace(keywords$singular, "bumblebees","bumblebee")
  keywords$singular<-str_replace(keywords$singular, "burrows","burrow")
  keywords$singular<-str_replace(keywords$singular, "cardamines","cardamine")
  keywords$singular<-str_replace(keywords$singular, "cardenolides","cardenolide")
  keywords$singular<-str_replace(keywords$singular, "carnivores","carnivore")
  keywords$singular<-str_replace(keywords$singular, "carotenoids","carotenoid")
  keywords$singular<-str_replace(keywords$singular, "cascades","cascade")
  keywords$singular<-str_replace(keywords$singular, "caterpillars","caterpillar")
  keywords$singular<-str_replace(keywords$singular, "cations","cation")
  keywords$singular<-str_replace(keywords$singular, "cetaceans","cetacean")
  keywords$singular<-str_replace(keywords$singular, "chains","chain")
  keywords$singular<-str_replace(keywords$singular, "changes","change")
  keywords$singular<-str_replace(keywords$singular, "characteristics","characteristic")
  keywords$singular<-str_replace(keywords$singular, "characters","character")
  keywords$singular<-str_replace(keywords$singular, "cheaters", "cheater")
  keywords$singular<-str_replace(keywords$singular, "chewers","chewer")
  keywords$singular<-str_replace(keywords$singular, "chironomids","chironomid")
  keywords$singular<-str_replace(keywords$singular, "chromosomes","chromosome")
  keywords$singular<-str_replace(keywords$singular, "cicadas","cicada")
  keywords$singular<-str_replace(keywords$singular, "cichlids","cichlid")
  keywords$singular<-str_replace(keywords$singular, "ciliates","ciliate")
  keywords$singular<-str_replace(keywords$singular, "cladistics","cladistic")
  keywords$singular<-str_replace(keywords$singular, "cladocerans","cladoceran")
  keywords$singular<-str_replace(keywords$singular, "climbers","climber")
  keywords$singular<-str_replace(keywords$singular, "clines","cline")
  keywords$singular<-str_replace(keywords$singular, "clocks","clock")
  keywords$singular<-str_replace(keywords$singular, "clones","clone")
  keywords$singular<-str_replace(keywords$singular, "cockroaches","cockroach")
  keywords$singular<-str_replace(keywords$singular, "coefficients","coefficient")
  keywords$singular<-str_replace(keywords$singular, "cohorts","cohort")
  keywords$singular<-str_replace(keywords$singular, "collections","collection")
  keywords$singular<-str_replace(keywords$singular, "the commons", "the common")
  keywords$singular<-str_replace(keywords$singular, "communities", "community")
  keywords$singular<-str_replace(keywords$singular, "comparisons","comparison")
  keywords$singular<-str_replace(keywords$singular, "competitors","competitor")
  keywords$singular<-str_replace(keywords$singular, "components","component")
  keywords$singular<-str_replace(keywords$singular, "compounds","compound")
  keywords$singular<-str_replace(keywords$singular, "concepts","concept")
  keywords$singular<-str_replace(keywords$singular, "conditions","condition")
  keywords$singular<-str_replace(keywords$singular, "conflicts", "conflict")
  keywords$singular<-str_replace(keywords$singular, "conifers","conifer")
  keywords$singular<-str_replace(keywords$singular, "consequences","consequence")
  keywords$singular<-str_replace(keywords$singular, "constraints","constraint")
  keywords$singular<-str_replace(keywords$singular, "consumers","consumer")
  keywords$singular<-str_replace(keywords$singular, "contents","content")
  keywords$singular<-str_replace(keywords$singular, "contrasts", "contrast")
  keywords$singular<-str_replace(keywords$singular, "coordinates","coordinate")
  keywords$singular<-str_replace(keywords$singular, "copepods","copepod")
  keywords$singular<-str_replace(keywords$singular, "corals","coral")
  keywords$singular<-str_replace(keywords$singular, "correlates","correlate")
  keywords$singular<-str_replace(keywords$singular, "correlations", "correlation")
  keywords$singular<-str_replace(keywords$singular, "corridors","corridor")
  keywords$singular<-str_replace(keywords$singular, "corrientes","corriente")
  keywords$singular<-str_replace(keywords$singular, "cottonwoods","cottonwood")
  keywords$singular<-str_replace(keywords$singular, "cotyledons","cotyledon")
  keywords$singular<-str_replace(keywords$singular, "counts","count")
  keywords$singular<-str_replace(keywords$singular, "covariates","covariate")
  keywords$singular<-str_replace(keywords$singular, "coyotes","coyote")
  keywords$singular<-str_replace(keywords$singular, "crickets","cricket")
  keywords$singular<-str_replace(keywords$singular, "crustaceans","crustacean")
  keywords$singular<-str_replace(keywords$singular, "cryptogams","cryptogam")
  keywords$singular<-str_replace(keywords$singular, "crystals","crystal")
  keywords$singular<-str_replace(keywords$singular, "currents","current")
  keywords$singular<-str_replace(keywords$singular, "cuttings","cutting")
  keywords$singular<-str_replace(keywords$singular, "cycles","cycle")
  keywords$singular<-str_replace(keywords$singular, "cyclones","cyclone")
  keywords$singular<-str_replace(keywords$singular, "cytogenetics","cytogenetic")
  keywords$singular<-str_replace(keywords$singular, "declines","decline")
  keywords$singular<-str_replace(keywords$singular, "decomposers","decomposer")
  keywords$singular<-str_replace(keywords$singular, "defenses", "defense")
  keywords$singular<-str_replace(keywords$singular, "deserts","desert")
  keywords$singular<-str_replace(keywords$singular, "detritivores","detritivore")
  keywords$singular<-str_replace(keywords$singular, "diatoms","diatom")
  keywords$singular<-str_replace(keywords$singular, "differences","difference")
  keywords$singular<-str_replace(keywords$singular, "differentials","differential")
  keywords$singular<-str_replace(keywords$singular, "dinoflagellates","dinoflagellate")
  keywords$singular<-str_replace(keywords$singular, "dinosaurs","dinosaur")
  keywords$singular<-str_replace(keywords$singular, "dipterocarps","dipterocarp")
  keywords$singular<-str_replace(keywords$singular, "diseases","disease")
  keywords$singular<-str_replace(keywords$singular, "dispersers","disperser")
  keywords$singular<-str_replace(keywords$singular, "distances","distance")
  keywords$singular<-str_replace(keywords$singular, "distributions", "distribution")
  keywords$singular<-str_replace(keywords$singular, "disturbances", "disturbance") 
  keywords$singular<-str_replace(keywords$singular, "dolphins","dolphin")
  keywords$singular<-str_replace(keywords$singular, "driptips","driptip")
  keywords$singular<-str_replace(keywords$singular, "drivers","driver")
  keywords$singular<-str_replace(keywords$singular, "drylands","dryland")
  keywords$singular<-str_replace(keywords$singular, "dynamics", "dynamic")
  keywords$singular<-str_replace(keywords$singular, "earthworms","earthworm")
  keywords$singular<-str_replace(keywords$singular, "ecdysteroids","ecdysteroid")
  keywords$singular<-str_replace(keywords$singular, "echinoderms","echinoderm")
  keywords$singular<-str_replace(keywords$singular, "ecoinformatics","ecoinformatic")
  keywords$singular<-str_replace(keywords$singular, "ecometabolomics","ecometabolomic")
  keywords$singular<-str_replace(keywords$singular, "economics","economic")
  keywords$singular<-str_replace(keywords$singular, "ecophylogenetics","ecophylogenetic")
  keywords$singular<-str_replace(keywords$singular, "ecoregions","ecoregion")
  keywords$singular<-str_replace(keywords$singular, "ecotones","ecotone")
  keywords$singular<-str_replace(keywords$singular, "ecotypes","ecotype")
  keywords$singular<-str_replace(keywords$singular, "ectomycorrhizas","ectomycorrhiza")
  keywords$singular<-str_replace(keywords$singular, "ectotherms","ectotherm")
  keywords$singular<-str_replace(keywords$singular, "effects", "effect")
  keywords$singular<-str_replace(keywords$singular, "elasmobranchs","elasmobranch")
  keywords$singular<-str_replace(keywords$singular, "elements","element")
  keywords$singular<-str_replace(keywords$singular, "embryos","embryo")
  keywords$singular<-str_replace(keywords$singular, "emissions","emission")
  keywords$singular<-str_replace(keywords$singular, "endemics","endemic")
  keywords$singular<-str_replace(keywords$singular, "endophytes","endophyte")
  keywords$singular<-str_replace(keywords$singular, "endosymbionts","endosymbiont")
  keywords$singular<-str_replace(keywords$singular, "energetics","energetic")
  keywords$singular<-str_replace(keywords$singular, "engineers","engineer")
  keywords$singular<-str_replace(keywords$singular, "enrichmens","enrichments")
  keywords$singular<-str_replace(keywords$singular, "environments","environment")
  keywords$singular<-str_replace(keywords$singular, "enzymes","enzyme")
  keywords$singular<-str_replace(keywords$singular, "epidemics","epidemic")
  keywords$singular<-str_replace(keywords$singular, "epigenetics","epigenetic")
  keywords$singular<-str_replace(keywords$singular, "epiphylls","epiphyll")
  keywords$singular<-str_replace(keywords$singular, "epiphytes","epiphyte")
  keywords$singular<-str_replace(keywords$singular, "equations","equation")
  keywords$singular<-str_replace(keywords$singular, "equivalents","equivalent")
  keywords$singular<-str_replace(keywords$singular, "ethics","ethic")
  keywords$singular<-str_replace(keywords$singular, "eukaryotes","eukaryote")
  keywords$singular<-str_replace(keywords$singular, "events","event")
  keywords$singular<-str_replace(keywords$singular, "exclosures","exclosure")
  keywords$singular<-str_replace(keywords$singular, "exotics","exotic")
  keywords$singular<-str_replace(keywords$singular, "experiments", "experiment")
  keywords$singular<-str_replace(keywords$singular, "extinctions","extinction")
  keywords$singular<-str_replace(keywords$singular, "extracts","extract")
  keywords$singular<-str_replace(keywords$singular, "extremes","extreme")
  keywords$singular<-str_replace(keywords$singular, "exudates","exudate")
  keywords$singular<-str_replace(keywords$singular, "factors", "factor")
  keywords$singular<-str_replace(keywords$singular, "faeces","feces")
  keywords$singular<-str_replace(keywords$singular, "feathers","feather")
  keywords$singular<-str_replace(keywords$singular, "feedbacks", "feedback")
  keywords$singular<-str_replace(keywords$singular, "felids","felid")
  keywords$singular<-str_replace(keywords$singular, "fences","fence")
  keywords$singular<-str_replace(keywords$singular, "fields","field")
  keywords$singular<-str_replace(keywords$singular, "filters","filter")
  keywords$singular<-str_replace(keywords$singular, "finches","finch")
  keywords$singular<-str_replace(keywords$singular, "fishes","fishe")
  keywords$singular<-str_replace(keywords$singular, "flavanoids","flavonoids")
  keywords$singular<-str_replace(keywords$singular, "flavonoids","flavonoid")
  keywords$singular<-str_replace(keywords$singular, "floaters","floater")
  keywords$singular<-str_replace(keywords$singular, "floodplains","floodplain")
  keywords$singular<-str_replace(keywords$singular, "floods","flood")
  keywords$singular<-str_replace(keywords$singular, "floristics","floristic")
  keywords$singular<-str_replace(keywords$singular, "flowers","flower")
  keywords$singular<-str_replace(keywords$singular, "fluctuations","fluctuation")
  keywords$singular<-str_replace(keywords$singular, "food webs", "food web")
  keywords$singular<-str_replace(keywords$singular, "forces","force")
  keywords$singular<-str_replace(keywords$singular, "forests", "forest")
  keywords$singular<-str_replace(keywords$singular, "forests", "forest")
  keywords$singular<-str_replace(keywords$singular, "fossils","fossil")
  keywords$singular<-str_replace(keywords$singular, "fragments","fragment")
  keywords$singular<-str_replace(keywords$singular, "frogs", "frog")
  keywords$singular<-str_replace(keywords$singular, "fronts", "front")
  keywords$singular<-str_replace(keywords$singular, "frugivores","frugivore")
  keywords$singular<-str_replace(keywords$singular, "fruits","fruit")
  keywords$singular<-str_replace(keywords$singular, "functions", "function")
  keywords$singular<-str_replace(keywords$singular, "fusions","fusion")
  keywords$singular<-str_replace(keywords$singular, "gametes","gamete")
  keywords$singular<-str_replace(keywords$singular, "gametophytes","gametophyte")
  keywords$singular<-str_replace(keywords$singular, "gardens","garden")
  keywords$singular<-str_replace(keywords$singular, "gastropods","gastropod")
  keywords$singular<-str_replace(keywords$singular, "geckos","gecko")
  keywords$singular<-str_replace(keywords$singular, "generalists","generalist")
  keywords$singular<-str_replace(keywords$singular, "generations","generation")
  keywords$singular<-str_replace(keywords$singular, "genetics","genetic")
  keywords$singular<-str_replace(keywords$singular, "genomics","genomic")
  keywords$singular<-str_replace(keywords$singular, "geostatistics","geostatistic")
  keywords$singular<-str_replace(keywords$singular, "gerbils","gerbil")
  keywords$singular<-str_replace(keywords$singular, "glaciations","glaciation")
  keywords$singular<-str_replace(keywords$singular, "glands","gland")
  keywords$singular<-str_replace(keywords$singular, "glucocorticoids","glucocorticoid")
  keywords$singular<-str_replace(keywords$singular, "glucosinolates","glucosinolate")
  keywords$singular<-str_replace(keywords$singular, "glycosides","glycoside")
  keywords$singular<-str_replace(keywords$singular, "gonads","gonad")
  keywords$singular<-str_replace(keywords$singular, "gophers","gopher")
  keywords$singular<-str_replace(keywords$singular, "gradients", "gradient")
  keywords$singular<-str_replace(keywords$singular, "graminoids","graminoid")
  keywords$singular<-str_replace(keywords$singular, "grasses","grass")
  keywords$singular<-str_replace(keywords$singular, "grasshoppers","grasshopper")
  keywords$singular<-str_replace(keywords$singular, "grasslands", "grassland")
  keywords$singular<-str_replace(keywords$singular, "grasslands", "grassland")
  keywords$singular<-str_replace(keywords$singular, "grasslands", "grassland")
  keywords$singular<-str_replace(keywords$singular, "grazers","grazer")
  keywords$singular<-str_replace(keywords$singular, "groups","group")
  keywords$singular<-str_replace(keywords$singular, "groves","grove")
  keywords$singular<-str_replace(keywords$singular, "guilds","guild")
  keywords$singular<-str_replace(keywords$singular, "gymnosperms","gymnosperm")
  keywords$singular<-str_replace(keywords$singular, "habitats","habitat")
  keywords$singular<-str_replace(keywords$singular, "habits","habit")
  keywords$singular<-str_replace(keywords$singular, "halophytes","halophyte")
  keywords$singular<-str_replace(keywords$singular, "handicaps","handicap")
  keywords$singular<-str_replace(keywords$singular, "hatchlings","hatchling")
  keywords$singular<-str_replace(keywords$singular, "hawkmoths","hawkmoth")
  keywords$singular<-str_replace(keywords$singular, "hazards","hazard")
  keywords$singular<-str_replace(keywords$singular, "heatwaves","heatwave")
  keywords$singular<-str_replace(keywords$singular, "helminths","helminth")
  keywords$singular<-str_replace(keywords$singular, "helpers","helper")
  keywords$singular<-str_replace(keywords$singular, "hemiepiphytes","hemiepiphyte")
  keywords$singular<-str_replace(keywords$singular, "herbivores", "herbivore")
  keywords$singular<-str_replace(keywords$singular, "hermaphrodites","hermaphrodite")
  keywords$singular<-str_replace(keywords$singular, "himalayas","himalaya")
  keywords$singular<-str_replace(keywords$singular, "histories","history")
  keywords$singular<-str_replace(keywords$singular, "honeybees","honeybee")
  keywords$singular<-str_replace(keywords$singular, "hormones","hormone")
  keywords$singular<-str_replace(keywords$singular, "hornbills","hornbill")
  keywords$singular<-str_replace(keywords$singular, "hostraces", "hostrace")
  keywords$singular<-str_replace(keywords$singular, "hotspots", "hotspot")
  keywords$singular<-str_replace(keywords$singular, "humans","human")
  keywords$singular<-str_replace(keywords$singular, "hurricanes","hurricane")
  keywords$singular<-str_replace(keywords$singular, "hybrids","hybrid")
  keywords$singular<-str_replace(keywords$singular, "hydrocarbons","hydrocarbon")
  keywords$singular<-str_replace(keywords$singular, "hydroids","hydroid")
  keywords$singular<-str_replace(keywords$singular, "hypotheses", "hypothesis")
  keywords$singular<-str_replace(keywords$singular, "immunoglobulins","immunoglobulin")
  keywords$singular<-str_replace(keywords$singular, "impacts","impact")
  keywords$singular<-str_replace(keywords$singular, "indicators","indicator")
  keywords$singular<-str_replace(keywords$singular, "indices","index")
  keywords$singular<-str_replace(keywords$singular, "individuals","individual")
  keywords$singular<-str_replace(keywords$singular, "infections","infection")
  keywords$singular<-str_replace(keywords$singular, "innovations","innovation")
  keywords$singular<-str_replace(keywords$singular, "inputs","input")
  keywords$singular<-str_replace(keywords$singular, "inquilines","inquiline")
  keywords$singular<-str_replace(keywords$singular, "insectivores","insectivore")
  keywords$singular<-str_replace(keywords$singular, "insects","insect")
  keywords$singular<-str_replace(keywords$singular, "inselbergs","inselberg")
  keywords$singular<-str_replace(keywords$singular, "interactions", "interaction")
  keywords$singular<-str_replace(keywords$singular, "interactions", "interaction")
  keywords$singular<-str_replace(keywords$singular, "interactors","interactor")
  keywords$singular<-str_replace(keywords$singular, "intervals","interval")
  keywords$singular<-str_replace(keywords$singular, "introductions","introduction")
  keywords$singular<-str_replace(keywords$singular, "invasions", "invasion")
  keywords$singular<-str_replace(keywords$singular, "inversions","inversion")
  keywords$singular<-str_replace(keywords$singular, "ipms", "ipm")
  keywords$singular<-str_replace(keywords$singular, "islands", "island")
  keywords$singular<-str_replace(keywords$singular, "isotopes","isotope")
  keywords$singular<-str_replace(keywords$singular, "isozymes","isozyme")
  keywords$singular<-str_replace(keywords$singular, "juveniles","juvenile")
  keywords$singular<-str_replace(keywords$singular, "kinematics","kinematic")
  keywords$singular<-str_replace(keywords$singular, "ladybeetles","ladybeetle")
  keywords$singular<-str_replace(keywords$singular, "lagoons","lagoon")
  keywords$singular<-str_replace(keywords$singular, "landmarks","landmark")
  keywords$singular<-str_replace(keywords$singular, "landscapes", "landscape")
  keywords$singular<-str_replace(keywords$singular, "landslides","landslide")
  keywords$singular<-str_replace(keywords$singular, "leafhoppers","leafhopper")
  keywords$singular<-str_replace(keywords$singular, "leaves","leaf")
  keywords$singular<-str_replace(keywords$singular, "legumes","legume")
  keywords$singular<-str_replace(keywords$singular, "lemmings","lemming")
  keywords$singular<-str_replace(keywords$singular, "lemurs","lemur")
  keywords$singular<-str_replace(keywords$singular, "levels","level")
  keywords$singular<-str_replace(keywords$singular, "lianas","liana")
  keywords$singular<-str_replace(keywords$singular, "lichens","lichen")
  keywords$singular<-str_replace(keywords$singular, "life history", "life-history")
  keywords$singular<-str_replace(keywords$singular, "limits","limit")
  keywords$singular<-str_replace(keywords$singular, "limpets","limpet")
  keywords$singular<-str_replace(keywords$singular, "linkages", "linkage")
  keywords$singular<-str_replace(keywords$singular, "lipids","lipid")
  keywords$singular<-str_replace(keywords$singular, "litterbags", "litterbag")
  keywords$singular<-str_replace(keywords$singular, "livelihoods","livelihood")
  keywords$singular<-str_replace(keywords$singular, "liverworts","liverwort")
  keywords$singular<-str_replace(keywords$singular, "lizards", "lizard")
  keywords$singular<-str_replace(keywords$singular, "macrofossils","macrofossil")
  keywords$singular<-str_replace(keywords$singular, "macronutrients","macronutrient")
  keywords$singular<-str_replace(keywords$singular, "macrophytes","macrophyte")
  keywords$singular<-str_replace(keywords$singular, "malformations","malformation")
  keywords$singular<-str_replace(keywords$singular, "mammals", "mammal")
  keywords$singular<-str_replace(keywords$singular, "manakins","manakin")
  keywords$singular<-str_replace(keywords$singular, "mangrooves","mangroves")
  keywords$singular<-str_replace(keywords$singular, "mangroves","mangrove")
  keywords$singular<-str_replace(keywords$singular, "markers","marker")
  keywords$singular<-str_replace(keywords$singular, "markets","market")
  keywords$singular<-str_replace(keywords$singular, "marshes","marsh")
  keywords$singular<-str_replace(keywords$singular, "marsupials","marsupial")
  keywords$singular<-str_replace(keywords$singular, "matings","mating")
  keywords$singular<-str_replace(keywords$singular, "matrices","matrice")
  keywords$singular<-str_replace(keywords$singular, "meadows","meadow")
  keywords$singular<-str_replace(keywords$singular, "measles","measle")
  keywords$singular<-str_replace(keywords$singular, "mechanisms","mechanism")
  keywords$singular<-str_replace(keywords$singular, "meerkats","meerkat")
  keywords$singular<-str_replace(keywords$singular, "mesocosmos","mesocosms")
  keywords$singular<-str_replace(keywords$singular, "mesocosms","mesocosm")
  keywords$singular<-str_replace(keywords$singular, "mesograzers","mesograzer")
  keywords$singular<-str_replace(keywords$singular, "metabolites","metabolite")
  keywords$singular<-str_replace(keywords$singular, "metabolomics","metabolomic")
  keywords$singular<-str_replace(keywords$singular, "metals","metal")
  keywords$singular<-str_replace(keywords$singular, "methods", "method")
  keywords$singular<-str_replace(keywords$singular, "metrics","metric")
  keywords$singular<-str_replace(keywords$singular, "microarthropods","microarthropod")
  keywords$singular<-str_replace(keywords$singular, "microbes","microbe")
  keywords$singular<-str_replace(keywords$singular, "microcosms","microcosm")
  keywords$singular<-str_replace(keywords$singular, "microenvironments","microenvironment")
  keywords$singular<-str_replace(keywords$singular, "microhabitats","microhabitat")
  keywords$singular<-str_replace(keywords$singular, "microorganisms", "microorganism")
  keywords$singular<-str_replace(keywords$singular, "microsatellites","microsatellite")
  keywords$singular<-str_replace(keywords$singular, "microsites","microsite")
  keywords$singular<-str_replace(keywords$singular, "midges","midge")
  keywords$singular<-str_replace(keywords$singular, "migrans","migran")
  keywords$singular<-str_replace(keywords$singular, "milipedes","millipedes")
  keywords$singular<-str_replace(keywords$singular, "minerals","mineral")
  keywords$singular<-str_replace(keywords$singular, "miners","miner")
  keywords$singular<-str_replace(keywords$singular, "minisatellites","minisatellite")
  keywords$singular<-str_replace(keywords$singular, "mistletoes","mistletoe")
  keywords$singular<-str_replace(keywords$singular, "models", "model")
  keywords$singular<-str_replace(keywords$singular, "modifications","modification")
  keywords$singular<-str_replace(keywords$singular, "modules","module")
  keywords$singular<-str_replace(keywords$singular, "molluscs","mollusc")
  keywords$singular<-str_replace(keywords$singular, "mollusks","mollusc")
  keywords$singular<-str_replace(keywords$singular, "mollusks","mollusk")
  keywords$singular<-str_replace(keywords$singular, "moluscs","mollusc")
  keywords$singular<-str_replace(keywords$singular, "monkeys","monkey")
  keywords$singular<-str_replace(keywords$singular, "monocultures","monoculture") 
  keywords$singular<-str_replace(keywords$singular, "monoterpenes","monoterpene")
  keywords$singular<-str_replace(keywords$singular, "morphometics","morphometrics")
  keywords$singular<-str_replace(keywords$singular, "morphometrics","morphometric")
  keywords$singular<-str_replace(keywords$singular, "morphs","morph")
  keywords$singular<-str_replace(keywords$singular, "mosquitoes","mosquitoe")
  keywords$singular<-str_replace(keywords$singular, "mosses","moss")
  keywords$singular<-str_replace(keywords$singular, "mountains","mountain")
  keywords$singular<-str_replace(keywords$singular, "movements","movement")
  keywords$singular<-str_replace(keywords$singular, "mussels","mussel")
  keywords$singular<-str_replace(keywords$singular, "mutations","mutation")
  keywords$singular<-str_replace(keywords$singular, "mutualisms","mutualism")
  keywords$singular<-str_replace(keywords$singular, "mycorrhizas","mycorrhizae")
  keywords$singular<-str_replace(keywords$singular, "myrmecophytes","myrmecophyte")
  keywords$singular<-str_replace(keywords$singular, "nectaries", "nectary")
  keywords$singular<-str_replace(keywords$singular, "nematodes","nematode")
  keywords$singular<-str_replace(keywords$singular, "neotropics","neotropic")
  keywords$singular<-str_replace(keywords$singular, "networks", "network")
  keywords$singular<-str_replace(keywords$singular, "niches","niche")
  keywords$singular<-str_replace(keywords$singular, "norms", "norm")
  keywords$singular<-str_replace(keywords$singular, "numbers","number")
  keywords$singular<-str_replace(keywords$singular, "nutrients","nutrient")
  keywords$singular<-str_replace(keywords$singular, "odonates","odonate")
  keywords$singular<-str_replace(keywords$singular, "oligochaetes","oligochaets")
  keywords$singular<-str_replace(keywords$singular, "opossums","possums")
  keywords$singular<-str_replace(keywords$singular, "orchids","orchid")
  keywords$singular<-str_replace(keywords$singular, "organisms", "organism")
  keywords$singular<-str_replace(keywords$singular, "ornaments","ornament")
  keywords$singular<-str_replace(keywords$singular, "otoliths","otolith")
  keywords$singular<-str_replace(keywords$singular, "otters","otter")
  keywords$singular<-str_replace(keywords$singular, "outbreaks", "outbreak")
  keywords$singular<-str_replace(keywords$singular, "oysters","oyster")
  keywords$singular<-str_replace(keywords$singular, "parameters","parameter")
  keywords$singular<-str_replace(keywords$singular, "parasites", "parasite")
  keywords$singular<-str_replace(keywords$singular, "parasitoids", "parasitoid")
  keywords$singular<-str_replace(keywords$singular, "parrots","parrot")
  keywords$singular<-str_replace(keywords$singular, "passerines","passerine")
  keywords$singular<-str_replace(keywords$singular, "pastures","pasture")
  keywords$singular<-str_replace(keywords$singular, "patens","paten")
  keywords$singular<-str_replace(keywords$singular, "pathogens", "pathogen")
  keywords$singular<-str_replace(keywords$singular, "patterns","pattern")
  keywords$singular<-str_replace(keywords$singular, "peatlands","peatland")
  keywords$singular<-str_replace(keywords$singular, "penguins","penguin")
  keywords$singular<-str_replace(keywords$singular, "perceptions","perception")
  keywords$singular<-str_replace(keywords$singular, "perturbations","perturbation")
  keywords$singular<-str_replace(keywords$singular, "phenolics","phenolic")
  keywords$singular<-str_replace(keywords$singular, "phenols","phenol")
  keywords$singular<-str_replace(keywords$singular, "phenotypes", "phenotype")
  keywords$singular<-str_replace(keywords$singular, "pheromones","pheromone")
  keywords$singular<-str_replace(keywords$singular, "photographs","photograph")
  keywords$singular<-str_replace(keywords$singular, "phylogenetics","phylogenetic")
  keywords$singular<-str_replace(keywords$singular, "phylogenomics","phylogenomic")
  keywords$singular<-str_replace(keywords$singular, "phytochemicals","phytochemical")
  keywords$singular<-str_replace(keywords$singular, "pigments","pigment")
  keywords$singular<-str_replace(keywords$singular, "pinnipeds","pinniped")
  keywords$singular<-str_replace(keywords$singular, "pioneers","pioneer")
  keywords$singular<-str_replace(keywords$singular, "pipiens","pipien")
  keywords$singular<-str_replace(keywords$singular, "plains","plain")
  keywords$singular<-str_replace(keywords$singular, "plantations","plantation")
  keywords$singular<-str_replace(keywords$singular, "planthoppers","planthopper")
  keywords$singular<-str_replace(keywords$singular, "pollinators","pollinator")
  keywords$singular<-str_replace(keywords$singular, "polychaetes","polychaete")
  keywords$singular<-str_replace(keywords$singular, "polymorphisms", "polymorphism")
  keywords$singular<-str_replace(keywords$singular, "polyphenols","polyphenol")
  keywords$singular<-str_replace(keywords$singular, "pools", "pool")
  keywords$singular<-str_replace(keywords$singular, "populations", "population")
  keywords$singular<-str_replace(keywords$singular, "predators", "predator")
  keywords$singular<-str_replace(keywords$singular, "predictors","predictor")
  keywords$singular<-str_replace(keywords$singular, "preferences","preference")
  keywords$singular<-str_replace(keywords$singular, "primates","primate")
  keywords$singular<-str_replace(keywords$singular, "processes","process")
  keywords$singular<-str_replace(keywords$singular, "producers","producer")
  keywords$singular<-str_replace(keywords$singular, "products", "product")
  keywords$singular<-str_replace(keywords$singular, "propagules","propagule")
  keywords$singular<-str_replace(keywords$singular, "proteomics","proteomic")
  keywords$singular<-str_replace(keywords$singular, "protists","protist")
  keywords$singular<-str_replace(keywords$singular, "psittacids","psittacid")
  keywords$singular<-str_replace(keywords$singular, "pteridophytes","pteridophyte")
  keywords$singular<-str_replace(keywords$singular, "ranges", "range")
  keywords$singular<-str_replace(keywords$singular, "raptors","raptor")
  keywords$singular<-str_replace(keywords$singular, "rates", "rate")
  keywords$singular<-str_replace(keywords$singular, "ratios", "ratio")
  keywords$singular<-str_replace(keywords$singular, "rearrangements","rearrangement")
  keywords$singular<-str_replace(keywords$singular, "records","record")
  keywords$singular<-str_replace(keywords$singular, "reefs", "reef")
  keywords$singular<-str_replace(keywords$singular, "reefs", "reef")
  keywords$singular<-str_replace(keywords$singular, "refuges","refuge")
  keywords$singular<-str_replace(keywords$singular, "regimes","regime")
  keywords$singular<-str_replace(keywords$singular, "relations","relation")
  keywords$singular<-str_replace(keywords$singular, "relationships", "relationship")
  keywords$singular<-str_replace(keywords$singular, "reptiles","reptile")
  keywords$singular<-str_replace(keywords$singular, "reserves","reserve")
  keywords$singular<-str_replace(keywords$singular, "resources", "resource")
  keywords$singular<-str_replace(keywords$singular, "responses", "response")
  keywords$singular<-str_replace(keywords$singular, "rhizomes","rhizome")
  keywords$singular<-str_replace(keywords$singular, "rivers","river")
  keywords$singular<-str_replace(keywords$singular, "rodents","rodent")
  keywords$singular<-str_replace(keywords$singular, "rotifers","rotifer")
  keywords$singular<-str_replace(keywords$singular, "salamanders","salamander")
  keywords$singular<-str_replace(keywords$singular, "salmonids","salmonid")
  keywords$singular<-str_replace(keywords$singular, "sanctions","sanction")
  keywords$singular<-str_replace(keywords$singular, "saplings","sapling")
  keywords$singular<-str_replace(keywords$singular, "savannahs", "savanna")
  keywords$singular<-str_replace(keywords$singular, "savannahs", "savanna")
  keywords$singular<-str_replace(keywords$singular, "savannas", "savanna")
  keywords$singular<-str_replace(keywords$singular, "savannas", "savanna")
  keywords$singular<-str_replace(keywords$singular, "scientometrics","scientometric")
  keywords$singular<-str_replace(keywords$singular, "scorpiones","scorpions")
  keywords$singular<-str_replace(keywords$singular, "scorpions","scorpion")
  keywords$singular<-str_replace(keywords$singular, "seagrasses","seagrass")
  keywords$singular<-str_replace(keywords$singular, "seamounts","seamount")
  keywords$singular<-str_replace(keywords$singular, "seasons","season")
  keywords$singular<-str_replace(keywords$singular, "seastars","seastar")
  keywords$singular<-str_replace(keywords$singular, "seaweeds","seaweed")
  keywords$singular<-str_replace(keywords$singular, "sediments","sediment")
  keywords$singular<-str_replace(keywords$singular, "seedlings","seedling")
  keywords$singular<-str_replace(keywords$singular, "services", "service")
  keywords$singular<-str_replace(keywords$singular, "shadows","shadow")
  keywords$singular<-str_replace(keywords$singular, "sharks","shark")
  keywords$singular<-str_replace(keywords$singular, "shifts","shift")
  keywords$singular<-str_replace(keywords$singular, "shredders","shredder")
  keywords$singular<-str_replace(keywords$singular, "shrews","shrew")
  keywords$singular<-str_replace(keywords$singular, "shrimps","shrimp")
  keywords$singular<-str_replace(keywords$singular, "shrublands","shrubland")
  keywords$singular<-str_replace(keywords$singular, "shrubs","shrub")
  keywords$singular<-str_replace(keywords$singular, "siderophores","siderophore")
  keywords$singular<-str_replace(keywords$singular, "signals","signal")
  keywords$singular<-str_replace(keywords$singular, "simulans","simulan")
  keywords$singular<-str_replace(keywords$singular, "simulations", "simulation")
  keywords$singular<-str_replace(keywords$singular, "skinks","skink")
  keywords$singular<-str_replace(keywords$singular, "snails","snail")
  keywords$singular<-str_replace(keywords$singular, "snakes","snake")
  keywords$singular<-str_replace(keywords$singular, "spacers", "spacer")
  keywords$singular<-str_replace(keywords$singular, "specialists","specialist")
  keywords$singular<-str_replace(keywords$singular, "specimens","specimen")
  keywords$singular<-str_replace(keywords$singular, "spiders","spider")
  keywords$singular<-str_replace(keywords$singular, "spines","spine")
  keywords$singular<-str_replace(keywords$singular, "splendens","splenden")
  keywords$singular<-str_replace(keywords$singular, "sponges","sponge")
  keywords$singular<-str_replace(keywords$singular, "spores","spore")
  keywords$singular<-str_replace(keywords$singular, "sprouts","sprout")
  keywords$singular<-str_replace(keywords$singular, "squamates","squamate")
  keywords$singular<-str_replace(keywords$singular, "squirrels","squirrel")
  keywords$singular<-str_replace(keywords$singular, "states","state")
  keywords$singular<-str_replace(keywords$singular, "statistics","statistic")
  keywords$singular<-str_replace(keywords$singular, "sticklebacks","stickleback")
  keywords$singular<-str_replace(keywords$singular, "stocks","stock")
  keywords$singular<-str_replace(keywords$singular, "strategies", "strategy")
  keywords$singular<-str_replace(keywords$singular, "streams","stream")
  keywords$singular<-str_replace(keywords$singular, "stressors","stressor")
  keywords$singular<-str_replace(keywords$singular, "structures","structure")
  keywords$singular<-str_replace(keywords$singular, "sugars","sugar")
  keywords$singular<-str_replace(keywords$singular, "sunflecks","sunfleck")
  keywords$singular<-str_replace(keywords$singular, "swamps","swamp")
  keywords$singular<-str_replace(keywords$singular, "symbionts","symbiont")
  keywords$singular<-str_replace(keywords$singular, "symbioses","symbiosis")
  keywords$singular<-str_replace(keywords$singular, "syndromes","syndrome")
  keywords$singular<-str_replace(keywords$singular, "systematics","systematic")
  keywords$singular<-str_replace(keywords$singular, "systems", "system")
  keywords$singular<-str_replace(keywords$singular, "systems", "system")
  keywords$singular<-str_replace(keywords$singular, "systems", "system")
  keywords$singular<-str_replace(keywords$singular, "tables","table")
  keywords$singular<-str_replace(keywords$singular, "tactics","tactic")
  keywords$singular<-str_replace(keywords$singular, "tadpoles","tadpole")
  keywords$singular<-str_replace(keywords$singular, "tannins", "tannin")
  keywords$singular<-str_replace(keywords$singular, "tannins", "tannin")
  keywords$singular<-str_replace(keywords$singular, "termites","termite")
  keywords$singular<-str_replace(keywords$singular, "terpenes","terpene")
  keywords$singular<-str_replace(keywords$singular, "terpenoids", "terpeniod")
  keywords$singular<-str_replace(keywords$singular, "threats","threat")
  keywords$singular<-str_replace(keywords$singular, "thresholds","threshold")
  keywords$singular<-str_replace(keywords$singular, "thrips","thrip")
  keywords$singular<-str_replace(keywords$singular, "toxins","toxin")
  keywords$singular<-str_replace(keywords$singular, "trade offs", "tradeoff")
  keywords$singular<-str_replace(keywords$singular, "trade-off", "tradeoff")
  keywords$singular<-str_replace(keywords$singular, "trade-offs", "tradeoff")
  keywords$singular<-str_replace(keywords$singular, "tradeoffs", "tradeoff")
  keywords$singular<-str_replace(keywords$singular, "traits", "trait")
  keywords$singular<-str_replace(keywords$singular, "transcriptomics","transcriptomic")
  keywords$singular<-str_replace(keywords$singular, "traps","trap")
  keywords$singular<-str_replace(keywords$singular, "treefalls", "treefall")
  keywords$singular<-str_replace(keywords$singular, "trees", "tree")
  keywords$singular<-str_replace(keywords$singular, "trematodes","trematode")
  keywords$singular<-str_replace(keywords$singular, "trends","trend")
  keywords$singular<-str_replace(keywords$singular, "trials","trial")
  keywords$singular<-str_replace(keywords$singular, "trichomes","trichome")
  keywords$singular<-str_replace(keywords$singular, "tropics","tropic")
  keywords$singular<-str_replace(keywords$singular, "turtles","turtle")
  keywords$singular<-str_replace(keywords$singular, "ungulates","ungulate")
  keywords$singular<-str_replace(keywords$singular, "units", "unit")
  keywords$singular<-str_replace(keywords$singular, "urchins","urchin")
  keywords$singular<-str_replace(keywords$singular, "values", "value")
  keywords$singular<-str_replace(keywords$singular, "variables","variable")
  keywords$singular<-str_replace(keywords$singular, "vectors","vector")
  keywords$singular<-str_replace(keywords$singular, "viruses","viruse")
  keywords$singular<-str_replace(keywords$singular, "visitors","visitor")
  keywords$singular<-str_replace(keywords$singular, "volatiles", "volatile")
  keywords$singular<-str_replace(keywords$singular, "volcanoes","volcanos")
  keywords$singular<-str_replace(keywords$singular, "vultures","vulture")
  keywords$singular<-str_replace(keywords$singular, "waders","wader")
  keywords$singular<-str_replace(keywords$singular, "weapons","weapon")
  keywords$singular<-str_replace(keywords$singular, "weevils","weevil")
  keywords$singular<-str_replace(keywords$singular, "wetlands","wetland")
  keywords$singular<-str_replace(keywords$singular, "wolves","wolf")
  keywords$singular<-str_replace(keywords$singular, "woodlands","woodland")
  keywords$singular<-str_replace(keywords$singular, "zoonoses","zoonosis")
  
  # TODO:
  # pgls
  # mvgls
  # pgls model
  # phylogenetic gls
  # probgls
  
  # DONE
  # generalized least squares gls
  # phylogenetic generalized least squares gls
  # phylogenetic generalized least squares pgls
  
  
  
  # keywords$singular<-gsub("capture-recapture", "capture recapture",keywords$singular)
  keywords$singular<-gsub(" dmii", "",keywords$singular)
  keywords$singular<-gsub(" dmiis", "",keywords$singular)
  keywords$singular<-gsub("above and below-ground", "aboveground and belowground",keywords$singular)
  keywords$singular<-gsub("abundances", "abundance",keywords$singular)
  keywords$singular<-gsub("amerindians", "amerindians",keywords$singular)
  keywords$singular<-gsub("below-ground", "belowground",keywords$singular)
  keywords$singular<-gsub("bottom up", "bottomup",keywords$singular)
  keywords$singular<-gsub("bottom-up", "bottomup",keywords$singular)
  keywords$singular<-gsub("cannonical", "canonical",keywords$singular)
  keywords$singular<-gsub("curves", "curve",keywords$singular)
  keywords$singular<-gsub("databases", "database",keywords$singular)
  keywords$singular<-gsub("differences", "difference",keywords$singular)
  keywords$singular<-gsub("dry forest", "dryforest",keywords$singular)
  keywords$singular<-gsub("dynamics", "dynamic",keywords$singular)
  keywords$singular<-gsub("hotspots", "hotspot",keywords$singular)
  keywords$singular<-gsub("land-use", "landuse",keywords$singular)
  keywords$singular<-gsub("least squares gls", "least square",keywords$singular)
  keywords$singular<-gsub("least squares pgls", "least square",keywords$singular)
  keywords$singular<-gsub("least squares", "least square",keywords$singular)
  keywords$singular<-gsub("least squares", "least square",keywords$singular)
  keywords$singular<-gsub("life history", "lifehistory",keywords$singular)
  keywords$singular<-gsub("life history", "lifehistory",keywords$singular)
  keywords$singular<-gsub("life-history", "lifehistory",keywords$singular)
  keywords$singular<-gsub("monocots", "monocot",keywords$singular)
  keywords$singular<-gsub("mutlti-event", "mutltievent",keywords$singular)
  keywords$singular<-gsub("mutualists", "mutualist",keywords$singular)
  keywords$singular<-gsub("nectarivores", "nectarivore",keywords$singular)
  keywords$singular<-gsub("outcrops", "outcrops",keywords$singular)
  keywords$singular<-gsub("plasmids", "plasmid",keywords$singular)
  keywords$singular<-gsub("points", "point",keywords$singular)
  keywords$singular<-gsub("polypores", "polypore",keywords$singular)
  keywords$singular<-gsub("proteins", "protein",keywords$singular)
  keywords$singular<-gsub("ramets", "ramet",keywords$singular)
  keywords$singular<-gsub("rangelands", "rangelands",keywords$singular)
  keywords$singular<-gsub("reservoirs", "reservoir",keywords$singular)
  keywords$singular<-gsub("resources", "resource",keywords$singular)
  keywords$singular<-gsub("rock outcrops", "rock outcrop",keywords$singular)
  keywords$singular<-gsub("rocky outcrop", "rock outcrop",keywords$singular)
  keywords$singular<-gsub("rocky outcrops", "rock outcrop",keywords$singular)
  keywords$singular<-gsub("scenarios", "scenario",keywords$singular)
  keywords$singular<-gsub("seeds", "seed",keywords$singular)
  keywords$singular<-gsub("semiochemicals", "semiochemical",keywords$singular)
  keywords$singular<-gsub("semivariograms", "semivariogram",keywords$singular)
  keywords$singular<-gsub("shores", "shore",keywords$singular)
  keywords$singular<-gsub("skewers", "skewer",keywords$singular)
  keywords$singular<-gsub("stable strategys ess", "stable strategy",keywords$singular)
  keywords$singular<-gsub("stable strategys", "stable strategy",keywords$singular)
  keywords$singular<-gsub("stones", "stone",keywords$singular)
  keywords$singular<-gsub("strengths", "strength",keywords$singular)
  keywords$singular<-gsub("strengths", "strength",keywords$singular)
  keywords$singular<-gsub("tetrapods", "tetrapod",keywords$singular)
  keywords$singular<-gsub("thorns", "thorn",keywords$singular)
  keywords$singular<-gsub("top down", "topdown",keywords$singular)
  keywords$singular<-gsub("top-down", "topdown",keywords$singular)
  keywords$singular<-gsub("transects", "transect",keywords$singular)
  keywords$singular<-gsub("vipers", "viper",keywords$singular)
  keywords$singular<-gsub("vocalizations", "vocalization",keywords$singular)
  keywords$singular<-gsub("vocalizations", "vocalizations",keywords$singular)
  keywords$singular<-gsub("volcanos", "volcano",keywords$singular)
  keywords$singular<-gsub("warblers", "warblers",keywords$singular)
  keywords$singular<-gsub("whelks", "whelks",keywords$singular)
  keywords$singular<-gsub("woodpeckers", "woodpeckers",keywords$singular)
  keywords$singular<-gsub("years", "year",keywords$singular)
  
  keywords<-keywords %>% mutate_all(trimws)    
  
  
  
  return(keywords)
}




